directories:
  output: release
  buildResources: build
appId: com.moodist.app
productName: Moodist
files:
  - filter:
      - dist/**
      - electron/**
      - package.json
extraMetadata:
  main: electron/main.cjs
asar: true
win:
  target:
    - nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 41.2.0
